resilio:
  image: pieghost/resilio-docker
  labels:
    io.rancher.scheduler.global: true
  environment:
    SYNC_SECRET: ${sync_secret}
  ports:
    - "55555:55555"
  volumes:
    - ${host_path}:/data
  restart: always
