.catalog:
  name: Resilio Sync
  version: 2.4.0-rancher1
  description: Resilio Sync (previously BitTorrent Sync)
  uuid: resilio-0
  questions:
    - variable: "host_path"
      label: Host path of /data folder to sync
      description: |
        A `storage` and `system` folders will be created for Resilio.
        Everything under the `storage` folder will be synced across hosts.
        e.g: `/var/lib/resilio`
      type: string
      required: true
      default: "/var/lib/resilio"
    - variable: "sync_secret"
      label: "Secret for sync storage"
      required: true
      type: "string"
      description: "Generate with `docker run --rm -e SYNC_SECRET='NONE' pieghost/resilio-docker --generate-secret`"
