# drupal: TODO

nginx:
  image: nginx:alpine
  volumes:
    - /data/storage/conf.d/:/etc/nginx/conf.d:ro
    - /data/storage/www/:/var/www/html
  links:
    - php-lb:php-lb

nginx-lb:
  image: rancher/load-balancer-service
  ports:
    - 80:80
    - 443:80
  tty: true
  stdin_open: true
  links:
    - nginx:nginx
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.loadbalancer.ssl.ports: '443'

php-fpm:
  image: pieghost/php-alpine-mysql
  volumes:
    - /data/storage/www/:/var/www/html
  external_links:
    - percona/percona-lb:percona-lb

php-lb:
  image: rancher/load-balancer-service
  expose:
    - 9000:9000/tcp
  tty: true
  stdin_open: true
  links:
    - php-fpm:php-fpm
  labels:
    io.rancher.scheduler.global: 'true'
