.catalog:
  name: drupal + nginx + php-fpm
  version: 8.0-rancher1
  description: drupal + nginx + php-fpm
  uuid: drupal-0
  questions:
    - variable: "domain_name"
      label: "Domain name of this website"
      required: true
      type: "string"
      description: "Domain name of this website"

nginx:
  scale: 3
  health_check:
    port: 80
    interval: 5000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2

php-fpm:
  scale: 3
  health_check:
    port: 9000
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2

# drupal: TODO

