nginx:
  image: nginx:alpine
  volumes:
    - ${nginx_confd_path}:/etc/nginx/conf.d:ro
    - ${webroot_path}:/var/www/html
  links:
    - php-lb:php-lb
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.scheduler.affinity:host_label_ne: webserver=false

nginx-lb:
  image: rancher/load-balancer-service
  ports:
    - 80:80
    - 443:80
  tty: true
  stdin_open: true
  links:
    - nginx:nginx
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.loadbalancer.ssl.ports: '443'
    io.rancher.scheduler.affinity:host_label_ne: webserver=false,ports_available=false

php-fpm:
  image: pieghost/php-alpine-mysql
  volumes:
    - ${webroot_path}:/var/www/html
  external_links:
    - percona/percona-lb:percona-lb
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.scheduler.affinity:host_label_ne: webserver=false

php-lb:
  image: rancher/load-balancer-service
  expose:
    - 9000:9000/tcp
  tty: true
  stdin_open: true
  links:
    - php-fpm:php-fpm
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label_ne: webserver=false
